# Test Configuration - Saskatchewan Items 1808-1946
# For testing the pipeline with a focused dataset

# Paths to existing component repositories
components:
  downloader_repo: /home/jic823/projects/def-jic823/InternetArchive
  olmocr_repo: /home/jic823/projects/def-jic823/cluster/olmocr

# Working directories
directories:
  # Use separate directory for test runs
  pdf_dir: /home/jic823/projects/def-jic823/pdfs_sask_test
  database: /home/jic823/projects/def-jic823/InternetArchive/archive_tracking.db

# Batch processing settings
batching:
  # Start small for testing
  batch_size: 10  # Process 10 items per batch for testing
  total_items: 50  # Test with 50 items
  batch_delay: 60  # 1 minute between batches

# Download phase settings
download:
  # Path to pre-fetched identifiers file
  identifiers_file: /home/jic823/projects/def-jic823/pdfs_sask_test/identifiers.json
  delay: 0.05
  download_all_pdfs: false  # Only download the main PDF, not _text.pdf versions
  subcollection: saskatchewan_1808_1946

# OCR phase settings
ocr:
  max_pdfs_per_chunk: 200
  # Legacy fallback for page-count based chunking
  # max_pages_per_chunk: 1500
  workers: auto
  pages_per_group: auto
  max_wait_hours: 12

# Ingestion phase settings
ingestion:
  parse_jsonl: true
  verify_data: true

# Cleanup phase settings
cleanup:
  auto_delete: true  # Enable auto-delete to prevent disk full
  grace_period_days: 0  # Delete immediately after OCR ingestion
  require_confirmation: false  # No confirmation needed (automated)
  create_manifest: true

# SLURM settings
slurm:
  email: jic823@usask.ca
  account: def-jic823
  time_limits:
    download: "04:00:00"
    ocr: "08:00:00"
    ingest: "02:00:00"
    cleanup: "01:00:00"

# Safety settings
safety:
  require_ocr_completed: true
  require_ocr_data_in_db: true
  require_valid_json: true
  max_deletions_per_run: 2000  # Allow cleanup of full batches

# Logging
logging:
  level: DEBUG  # More verbose for testing
  log_dir: /home/jic823/projects/def-jic823/archive-olm-pipeline/logs
